security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8080/auth/realms/master/protocol/openid-connect/userinfo
      
management:
  security:
    enabled: false      
    
logging:
  level:
    org:
      springframework:
        security: debug
        web: debug
        data: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
