---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://peer2/eureka/,http://peer3/eureka/

server:
  port: 8761

---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://peer1/eureka/,http://peer3/eureka/
server:
  port: 8762

---
spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://peer1/eureka/,http://peer2/eureka/
server:
  port: 8763
