server:
  port: 28080

spring:
  datasource:
    url: jdbc:mysql://localhost/master?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
