server:
  port: 28080

spring:
  datasource:
    url: jdbc:mysql://localhost/master?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

keycloak:
  ribbon:
    listOfServers: http://localhost:8080/auth
  admin:
    username: admin
    password: admin
